document.addEventListener('DOMContentLoaded', () => {

    // 1. Get Vehicle ID from URL generated by the QR Sticker
    const urlParams = new URLSearchParams(window.location.search);
    const vehicleId = urlParams.get('id');

    if (!vehicleId) {
        showError('לא נמצא מזהה רכב תקף בקישור.');
        return;
    }

    // 2. Fetch Data from Local Storage (Mocking a database fetch)
    const savedCars = JSON.parse(localStorage.getItem('userCars')) || [];
    const currentCar = savedCars.find(c => c.id == vehicleId);

    if (!currentCar) {
        showError('לא מצאנו רכב תואם במערכת שלנו.');
        return;
    }

    // 3. Render the Public Data
    renderPublicReport(currentCar);
});

function showError(msg) {
    document.getElementById('loading-screen').innerHTML = `
        <i class="fas fa-exclamation-triangle fa-3x text-danger mb-3"></i>
        <h4 class="text-dark fw-bold">${msg}</h4>
        <p class="text-muted mt-2">הקישור שנסרק אינו תקין או פג תוקף.</p>
    `;
}

function renderPublicReport(car) {

    // Header
    const brand = car.brandHeb || car.brand || 'רכב לא ידוע';
    const logoSrc = car.logo || 'images/logos/default.png';
    const year = car.year || '';

    document.getElementById('pr-logo').innerHTML = `<img src="${logoSrc}" alt="Logo">`;
    document.getElementById('pr-title').textContent = `${brand} ${car.model || ''}`;
    document.getElementById('pr-subtitle').textContent = `מספר רישוי: ${car.licensePlate} | שנת ייצור: ${year} | ${car.color || ''}`;

    // Key Stats
    document.getElementById('pr-km').textContent = car.km ? car.km.toLocaleString() : '--';

    // Test/MOT formatting
    let testStr = '--';
    if (car.testDate && car.testDate !== 'אין נתונים') {
        const parts = car.testDate.split('/');
        testStr = parts.length === 3 ? `${parts[1]}/${parts[2] || parts[0]}` : car.testDate;
    }
    document.getElementById('pr-test').textContent = testStr;

    // Reliability calculation logic matched from dashboard 
    // In a real app the server would send this integer. We mock it natively here.
    let relScore = calculateLocalReliability(car);
    document.getElementById('pr-reliability').textContent = relScore + '%';
    if (relScore >= 80) document.getElementById('pr-reliability').classList.add('text-success');

    // Total documented Expenses
    let totalExpenses = 0;
    if (car.treatments) car.treatments.forEach(t => { if (t.cost) totalExpenses += parseFloat(t.cost); });
    if (car.insurance && car.insurance.cost) totalExpenses += parseFloat(car.insurance.cost);
    document.getElementById('pr-expenses').textContent = '₪' + totalExpenses.toLocaleString();

    // Technical Specs
    document.getElementById('pr-hp').textContent = car.horsePower || '--';
    document.getElementById('pr-engine').textContent = car.engineVolume || '--';
    document.getElementById('pr-tires-f').textContent = car.tireFront || '--';
    document.getElementById('pr-tires-r').textContent = car.tireRear || '--';
    document.getElementById('pr-fuel-type').textContent = car.fuelType || '--';

    // --- Photo Gallery ---
    const gallery = car.gallery || [];
    const galleryContainer = document.getElementById('publicGalleryContainer');
    const galleryGrid = document.getElementById('publicGalleryGrid');
    if (galleryContainer && galleryGrid && gallery.length > 0) {
        galleryContainer.classList.remove('d-none');
        galleryGrid.innerHTML = '';
        gallery.forEach(imgBase64 => {
            galleryGrid.innerHTML += `
                <div class="col-6 col-md-4">
                    <img src="${imgBase64}" class="img-fluid rounded border shadow-sm w-100" style="height: 180px; object-fit: cover; cursor: zoom-in;" onclick="window.open('${imgBase64}', '_blank')">
                </div>
            `;
        });
    }

    // --- Treatments Timeline ---
    const treatments = car.treatments || [];
    const tContainer = document.getElementById('pr-treatments-timeline');

    if (treatments.length > 0) {
        // Sort newest first
        treatments.sort((a, b) => new Date(b.date) - new Date(a.date));

        let html = '<div style="position: relative; margin-top: 10px;">';
        treatments.forEach(t => {
            let dParts = t.date ? t.date.split('-') : [];
            let displayDate = dParts.length === 3 ? `${dParts[2]}/${dParts[1]}/${dParts[0]}` : t.date;

            let verifiedHtml = t.invoice ?
                `<div class="verified-badge mt-2 shadow-sm"><i class="fas fa-check-circle me-1"></i> טיפול מאומת (הוזנה קבלה במקור)</div>` : '';

            let costHtml = t.cost ? `<div class="badge bg-light text-danger border mt-2 px-2 py-1"><i class="fas fa-shekel-sign me-1"></i> ${parseFloat(t.cost).toLocaleString()}</div>` : '';

            html += `
                <div class="timeline-item">
                    <div class="timeline-dot"></div>
                    <div class="report-card p-3 mb-3 border-0 bg-white" style="box-shadow: 0 4px 15px rgba(0,0,0,0.03);">
                        <div class="d-flex justify-content-between align-items-center mb-2">
                            <span class="text-secondary small fw-bold"><i class="far fa-calendar-alt me-1"></i> ${displayDate}</span>
                            <span class="badge bg-primary bg-opacity-10 text-primary border"><i class="fas fa-tachometer-alt me-1 text-primary"></i> ק"מ: ${t.km ? t.km.toLocaleString() : '-'}</span>
                        </div>
                        <h6 class="fw-bold text-dark m-0" style="font-size: 1.05rem;">${t.name || '-'}</h6>
                        <div class="text-muted small mt-1"><i class="fas fa-wrench me-1"></i> מוסך מבצע: ${t.garage || 'לא צוין'}</div>
                        <div class="d-flex gap-2 flex-wrap">
                            ${costHtml}
                            ${verifiedHtml}
                        </div>
                    </div>
                </div>
            `;
        });
        html += '</div>';
        tContainer.innerHTML = html;
    }

    // --- Insurance Data ---
    const ins = car.insurance || {};
    const iContainer = document.getElementById('pr-insurance-data');
    if (ins.company || ins.type) {
        let docsBtn = ins.invoice ? `<a href="${ins.invoice}" target="_blank" class="btn btn-sm btn-outline-primary rounded-pill px-3 mt-3"><i class="fas fa-file-contract me-1"></i> צפה בפוליסה מצורפת</a>` : '';
        iContainer.innerHTML = `
            <table class="table table-bordered table-custom">
                <tbody>
                    <tr>
                        <th style="width: 35%;">חברת ביטוח</th>
                        <td>${ins.company || '-'}</td>
                    </tr>
                    <tr>
                        <th>סוג פוליסה נוספת</th>
                        <td>${ins.type || 'חובה בלבד'}</td>
                    </tr>
                    <tr>
                        <th>תוקף חובה</th>
                        <td>${ins.mandatoryExp || '-'}</td>
                    </tr>
                    <tr>
                        <th>תוקף פוליסה נוספת</th>
                        <td>${ins.comprehensiveExp || '-'}</td>
                    </tr>
                    <tr>
                        <th class="text-danger">עלות ביטוחים כוללת</th>
                        <td class="fw-bold">₪${ins.cost ? parseFloat(ins.cost).toLocaleString() : '-'}</td>
                    </tr>
                </tbody>
            </table>
            ${docsBtn}
        `;
    }

    // --- Reports / Fines Data ---
    const reports = car.reports || [];
    const rContainer = document.getElementById('pr-reports-data');
    if (reports.length > 0) {
        let html = `
            <table class="table table-hover table-custom text-center">
                <thead><tr><th>תאריך עבירה</th><th>סוג</th><th>סכום לתשלום (₪)</th></tr></thead>
                <tbody>
        `;
        reports.forEach(r => {
            html += `<tr>
                <td>${r.date || '-'}</td>
                <td>${r.type || '-'}</td>
                <td class="text-danger fw-bold">${r.amount ? parseFloat(r.amount).toLocaleString() : '-'}</td>
            </tr>`;
        });
        html += `</tbody></table>`;
        rContainer.innerHTML = html;
    }

    // --- Fuel Data ---
    const fuels = car.fuelLog || [];
    const fContainer = document.getElementById('pr-fuel-data');
    if (fuels.length > 0) {
        // limit to last 5 for cleanliness
        fuels.sort((a, b) => new Date(b.date) - new Date(a.date));
        const recentFuels = fuels.slice(0, 5);
        let html = `
            <table class="table table-hover table-custom text-center">
                <thead><tr><th>תאריך תדלוק</th><th>כמות ליטרים</th><th>סה"כ שולם (₪)</th></tr></thead>
                <tbody>
        `;
        recentFuels.forEach(f => {
            html += `<tr>
                <td>${f.date || '-'}</td>
                <td><span class="badge bg-light text-dark">${f.liters || '-'} L</span></td>
                <td class="fw-bold">${f.cost ? parseFloat(f.cost).toLocaleString() : '-'}</td>
            </tr>`;
        });
        html += `</tbody></table>`;
        fContainer.innerHTML = html;
    }

    // --- Accidents Data ---
    const acc = car.accidents || [];
    const aContainer = document.getElementById('pr-accidents-data');
    if (acc.length > 0) {
        let html = `
            <table class="table table-hover table-custom text-center border-danger">
                <thead class="table-danger"><tr><th>תאריך דיווח</th><th>תיאור נזק / אירוע</th><th>עלות משוערת לנזק (₪)</th></tr></thead>
                <tbody>
        `;
        acc.forEach(a => {
            html += `<tr>
                <td>${a.date || '-'}</td>
                <td class="text-end">${a.description || '-'}</td>
                <td class="text-danger fw-bold">${a.damageCost ? parseFloat(a.damageCost).toLocaleString() : '-'}</td>
            </tr>`;
        });
        html += `</tbody></table>`;
        aContainer.innerHTML = html;
    }

    // Turn off loader
    setTimeout(() => {
        document.getElementById('loading-screen').style.display = 'none';
        document.getElementById('app-content').style.display = 'block';
    }, 400); // slight delay for visual smoothness
}

// Lightweight isolated scoring copy for landing page
function calculateLocalReliability(car) {
    let score = 20;

    // Treatments
    if (car.treatments && car.treatments.length > 0) {
        let treatmentsScore = Math.min((car.treatments.length / 5) * 30, 30);
        score += treatmentsScore;
    }

    // Insurance
    if (car.insurance) {
        const hasComprehensive = car.insurance.type === 'מקיף';
        const hasThirdParty = car.insurance.type === "צד ג'";
        if (hasComprehensive || hasThirdParty) {
            score += Math.min(25, 25);
        }
    }

    // Fuel Logs
    if (car.fuelLog && car.fuelLog.length > 0) {
        let fuelScore = Math.min((car.fuelLog.length / 5) * 15, 15);
        score += fuelScore;
    }

    // Test Validation (Future = 10 pts)
    if (car.testDate && car.testDate !== 'אין נתונים') {
        const dParts = car.testDate.split('/');
        let d = null;
        if (dParts.length === 3) {
            d = new Date(dParts[2], dParts[1] - 1, dParts[0]);
        } else if (dParts.length === 2) {
            // Assume 1st of month just for check
            d = new Date(dParts[1], dParts[0] - 1, 1);
        }

        if (d && d >= new Date()) {
            score += 10;
        }
    }

    return Math.round(score);
}
